version: '3.8'

services:
  db:
    image: postgres:15
    container_name: coffee-machine-db
    environment:
      POSTGRES_DB: coffee_machine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: karakesek
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
